name: Docker Test & Publish

on:
  push:
    tags:
      - "*"
  pull_request:
    branches:
      - "main"
    paths:
      - "Dockerfile"

permissions:
  contents: read
  packages: write

jobs:
  base:
    name: Test base image build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      # Configure build environment
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build the image
      - name: Build base image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          platforms: linux/amd64
          tags: ghcr.io/${{ github.repository }}-base:latest
          cache-from: type=gha,scope=buildx-base-multi-arch
          cache-to: type=gha,scope=buildx-base-multi-arch,mode=max

  publish:
    runs-on: self-hosted
    if: github.event_name != 'pull_request'
    name: Publish Docker images
    steps:
      # Configure build environment
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the image
      - name: Build base image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ghcr.io/${{ github.repository }}-base:latest

      # revoltchat/server
      - name: Docker meta
        id: meta-delta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}-server
      - name: Publish
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          file: crates/delta/Dockerfile
          tags: ${{ steps.meta-delta.outputs.tags }}
          build-args: |
            BASE_IMAGE=ghcr.io/${{ github.repository }}-base:latest
          labels: ${{ steps.meta-delta.outputs.labels }}

      # revoltchat/bonfire
      - name: Docker meta
        id: meta-bonfire
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}-bonfire
      - name: Publish
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          file: crates/bonfire/Dockerfile
          tags: ${{ steps.meta-bonfire.outputs.tags }}
          build-args: |
            BASE_IMAGE=ghcr.io/${{ github.repository }}-base:latest
          labels: ${{ steps.meta-bonfire.outputs.labels }}

      # revoltchat/autumn
      - name: Docker meta
        id: meta-autumn
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}-autumn
      - name: Publish
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          file: crates/services/autumn/Dockerfile
          tags: ${{ steps.meta-autumn.outputs.tags }}
          build-args: |
            BASE_IMAGE=ghcr.io/${{ github.repository }}-base:latest
          labels: ${{ steps.meta-autumn.outputs.labels }}

      # revoltchat/january
      - name: Docker meta
        id: meta-january
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}-january
      - name: Publish
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          file: crates/services/january/Dockerfile
          tags: ${{ steps.meta-january.outputs.tags }}
          build-args: |
            BASE_IMAGE=ghcr.io/${{ github.repository }}-base:latest
          labels: ${{ steps.meta-january.outputs.labels }}

      # revoltchat/gifbox
      - name: Docker meta
        id: meta-gifbox
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}-gifbox
      - name: Publish
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          file: crates/services/gifbox/Dockerfile
          tags: ${{ steps.meta-gifbox.outputs.tags }}
          build-args: |
            BASE_IMAGE=ghcr.io/${{ github.repository }}-base:latest
          labels: ${{ steps.meta-gifbox.outputs.labels }}

      # revoltchat/crond
      - name: Docker meta
        id: meta-crond
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}-crond
      - name: Publish
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          file: crates/daemons/crond/Dockerfile
          tags: ${{ steps.meta-crond.outputs.tags }}
          build-args: |
            BASE_IMAGE=ghcr.io/${{ github.repository }}-base:latest
          labels: ${{ steps.meta-crond.outputs.labels }}

      # revoltchat/pushd
      - name: Docker meta
        id: meta-pushd
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}-pushd
      - name: Publish
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          file: crates/daemons/pushd/Dockerfile
          tags: ${{ steps.meta-pushd.outputs.tags }}
          build-args: |
            BASE_IMAGE=ghcr.io/${{ github.repository }}-base:latest
          labels: ${{ steps.meta-pushd.outputs.labels }}
